micronaut:
  application:
    name: svampyrerna
  security:
    authentication: cookie
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/svampyrerna
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    dialect: POSTGRES

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.yml'
