micronaut:
  application:
    name: svampyrerna
  security:
    authentication: cookie
    interceptUrlMap:
      - pattern: "/swagger/**"
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: "/swagger-ui/**"
        httpMethod: GET
        access:
          - isAnonymous()
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: "${JDBC_DATABASE_URL}"
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.yml'
