micronaut:
  http:
    services:
      ping:
        url: "${PING_URL}"
  application:
    name: rallymontecarl
  security:
    authentication: cookie
    interceptUrlMap:
      - pattern: "/swagger/**"
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: "/swagger-ui/**"
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: "/public/**"
        httpMethod: GET
        access:
          - isAnonymous()
    redirect:
      login-failure: /login/authFailed
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        cookie:
          cookie-same-site: none
  router:
    static-resources:
      public:
        paths: classpath:public
        mapping: /public/**
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      single-header: true
      configurations:
        all:
          allowedOrigins:
            - https:\/\/([A-Za-z0-9\-_]*\\.)*herokuapp.com
            - http(s)?:\/\/localhost(:[0-9]*)?

datasources:
  default:
    url: "${JDBC_DATABASE_URL}"
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

liquibase:
  datasources:
    default:
      change-log: 'classpath:liquibase-changelog.yml'

endpoints:
  health:
    enabled: true
    sensitive: false

ping:
  enabled: false